services:
  nginx:
    image: marcusvxf/nginx:latest
    container_name: nginx

    ports:
      - '80:80'
      - '413:413'
    networks:
      service-connection:
        aliases:
          - service-connection

  api-node:
    image:
    command: npm run start
    container_name: api-node
    networks:
      service-connection:
        aliases:
          - service-connection
    expose:
      - '3000'
    environment:
      PORT: 3000
      ENVIRONMENT: prod
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public

  db:
    image: postgres:17-bookworm
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      service-connection:
        aliases:
          - service-connection

networks:
  service-connection:
    driver: bridge
