version: '3'

services:
  db:
    image: postgres:17-bookworm
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - default

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: bash -c "npx prisma generate && npm run dev"
    volumes:
      - .:/app
    networks:
      - default

volumes:
  db-data:

networks:
  default:
    driver: bridge
