name: WORKFLOW_CALL - Build and update docker image

on:
  workflow_call:
    inputs:
      version_code:
        required: true
        type: string
      path:
        required: false
        type: string
      context:
        required: false
        type: string
      docker_image_name:
        required: true
        type: string

    secrets:
      GH_TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_IMAGE_NAME:
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the target repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context || '.' }}
          file: ${{ inputs.path || 'Dockerfile' }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{inputs.docker_image_name}}:${{ inputs.version_code }}
