name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'front-end/**'

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          MIN_COVERAGE: 40
        run: npm run test
