name: Update Docker Compose file on prod

on:
  workflow_dispatch:
    inputs:
      update_envs:
        required: false
        default: false
        type: boolean
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - name: Log de informações do executor
        run: |
          echo "Usuário que executou: ${{ github.actor }}"
          echo "Repositório: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "SHA do commit: ${{ github.sha }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Data e hora UTC: $(date -u)"
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH with a passphrase
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY_FILE}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PROD_ENV_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with SCP
        run: |
          scp docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:~/application/
