name: WORKFLOW_CALL - SAST Analysis

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  sast:
    name: Analise sast
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Trivy Vulnerability Report
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          output: trivy-report.json
          format: json
          scan-ref: ./${{inputs.path}}
          exit-code: 0

      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 15

      - name: Fail build on High/Criticial Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'table'
          severity: HIGH CRITICAL
          scan-ref: ./${{inputs.path}}
          exit-code: 1
